server:
  port: 9000
  contextPath: /App


management:
  port: 9000
  contextPath: /Manage
  security:
    enabled: false

#Edit datasource URL to point to mysql database.
datasource:
  portfolioApp:
    url: jdbc:mysql://localhost:3306/portfolio?autoReconnect=true&useSSL=false
    username: portfolio
    password: portfolio
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: portfolio
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create-drop
      #hbm2ddl.method: none
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect